platform: x64

environment:
  matrix:
    #- DC: dmd
      #DReleaseType: releases
      #DVersion: 2.091.0
      #DSubversion:
      #arch: x64
      #dubArgs: --build-mode=singleFile
      #Ddflags: -lowmem
    #- DC: dmd
      #DReleaseType: releases
      #DVersion: 2.091.0
      #DSubversion:
      #arch: x86
      #dubArgs: --build-mode=singleFile
      #Ddflags: -lowmem
    #- DC: dmd
      #DReleaseType: releases
      #DVersion: 2.090.1
      #DSubversion:
      #arch: x64
      #dubArgs: --build-mode=singleFile
      #Ddflags: -lowmem
    #- DC: dmd
      #DReleaseType: releases
      #DVersion: 2.090.1
      #DSubversion:
      #arch: x86
      #dubArgs: --build-mode=singleFile
      #Ddflags: -lowmem
    #- DC: dmd
      #DReleaseType: releases
      #DVersion: 2.089.1
      #DSubversion:
      #arch: x64
      #dubArgs: --build-mode=singleFile
      #Ddflags: -lowmem
    #- DC: dmd
      #DReleaseType: releases
      #DVersion: 2.089.1
      #DSubversion:
      #arch: x86
      #dubArgs: --build-mode=singleFile
      #Ddflags: -lowmem
    - DC: dmd
      DReleaseType: releases
      DVersion: 2.084.0
      DSubversion:
      arch: x64
      dubArgs:
      Ddflags:
    - DC: dmd
      DReleaseType: releases
      DVersion: 2.084.0
      DSubversion:
      arch: x86
      dubArgs:
      Ddflags:
    #- DC: ldc
      #DVersion: 1.20.0
      #DSubversion:
      #arch: x64
      #dubArgs:
      #Ddflags:
    #- DC: ldc
      #DVersion: 1.19.0
      #DSubversion:
      #arch: x64
      #dubArgs:
      #Ddflags:
    - DC: ldc
      DVersion: 1.18.0
      DSubversion:
      arch: x64
      dubArgs:
      Ddflags:
    - DC: ldc
      DVersion: 1.14.0
      DSubversion:
      arch: x64
      dubArgs:
      Ddflags:

skip_tags: true
branches:
  except:
    - /circleci-.*/
    - /travis-.*/
    - gh-pages

artifacts:
  - path: kameloso.exe
    name: Normal build
  - path: kameloso-vanilla.exe
    name: Colourless vanilla build
  - path: kameloso-twitch.exe
    name: With Twitch bot
  - path: kameloso-dev.exe
    name: All-inclusive dev build (preferred when testing)

install:
  - ps: function SetUpDCompiler
        {
            $version = $env:DVersion;
            $subversion = $env:DSubversion;
            if($env:DC -eq "dmd"){
              $releasetype = $env:DReleaseType;
              Invoke-WebRequest "http://downloads.dlang.org/$($releasetype)/2.x/$($version)/dmd.$($version)$($subversion).windows.7z" -OutFile "c:\compiler.archive";
            }
            elseif($env:DC -eq "ldc"){
              $arch = $env:arch;
              Invoke-WebRequest "https://github.com/ldc-developers/ldc/releases/download/v$($version)$($subversion)/ldc2-$($version)$($subversion)-windows-$($arch).7z" -OutFile "c:\compiler.archive";
            }
            pushd c:\\;
            7z x compiler.archive > $null;
            popd;
        }
  - ps: SetUpDCompiler

before_build:
  - ps: $env:toolchain = "msvc";
  - ps: if($env:arch -eq "x86"){
            $env:compilersetupargs = "x86";
            $env:Darch = "x86";
            $env:DConf = "m32";
          }
        elseif($env:arch -eq "x64"){
            $env:compilersetupargs = "amd64";
            $env:Darch = "x86_64";
            $env:DConf = "m64";
        }
  - ps : if($env:DC -eq "dmd"){
           $path = $env:PATH;
           $env:PATH = "C:\dmd2\windows\bin;$($path)";
         }
         elseif($env:DC -eq "ldc"){
           $version = $env:DVersion;
           $subversion = $env:DSubversion;
           $arch = $env:arch;
           $path = $env:PATH;
           $env:PATH = "C:\ldc2-$($version)$($subversion)-windows-$($arch)\bin;$($path)";
           $env:DC = "ldc2";
         }
  - ps: $env:compilersetup = "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall";
  - '"%compilersetup%" %compilersetupargs%'

build_script:
 - echo dummy build script - dont remove me

test_script:
 - echo %PLATFORM%
 - echo %Darch%
 - echo %DC%
 - echo %PATH%
 - echo %dubArgs%
 - echo %Ddflags%
 - '%DC% --version'
 - dub --version
 - git clone https://github.com/zorael/lu.git
 - git clone https://github.com/zorael/dialect.git
 - dub add-local lu
 - dub add-local dialect
 - echo Full tests may fail due to https://issues.dlang.org/show_bug.cgi?id=20048
 - set DFLAGS = %Ddflags% -unittest
 - dub test           --arch=%Darch% --compiler=%DC% %dubArgs%
 - dub test  --nodeps --arch=%Darch% --compiler=%DC% %dubArgs% -c vanilla
 - set DFLAGS = %Ddflags%
 - dub build --nodeps --arch=%Darch% --compiler=%DC% %dubArgs% -b plain -c vanilla || true
 - dub build --nodeps --arch=%Darch% --compiler=%DC% %dubArgs% -b plain -c full || true
 - dub build --nodeps --arch=%Darch% --compiler=%DC% %dubArgs% -b plain -c dev || true
 - dub build --nodeps --arch=%Darch% --compiler=%DC% %dubArgs% -b release -c vanilla || true
 - dub build --nodeps --arch=%Darch% --compiler=%DC% %dubArgs% -b release -c full || true
 - dub build --nodeps --arch=%Darch% --compiler=%DC% %dubArgs% -b release -c dev || true
 - dub build --nodeps --arch=%Darch% --compiler=%DC% %dubArgs% -b debug -c vanilla
 - mv kameloso.exe kameloso-vanilla.exe
 - dub build --nodeps --arch=%Darch% --compiler=%DC% %dubArgs% -b debug -c dev
 - mv kameloso.exe kameloso-dev.exe
 - dub build --nodeps --arch=%Darch% --compiler=%DC% %dubArgs% -b debug -c twitch
 - mv kameloso.exe kameloso-twitch.exe
 - dub build --nodeps --arch=%Darch% --compiler=%DC% %dubArgs% -b debug -c full
 - #mv kameloso.exe kameloso-full.exe
